export type RootStackParamList = {
  Splash: undefined;
  Home: undefined;
  CustomerList: undefined;
  CreditList: undefined;
  PaymentList: undefined;
  CustomerDetail: { customerId: number };
  AddTransaction: { customerId?: number; mode: 'credit' | 'payment'; lockMode?: boolean };
  EditTransaction: { transactionId: number; mode: 'credit' | 'payment' };
  AddCustomer: { returnTo?: 'AddTransaction'; mode?: 'credit' | 'payment'; lockMode?: boolean } | undefined;
  EditCustomer: { customerId: number };
  CreditReports: undefined;
  Menu: undefined;
  AboutApp: undefined;
  PrivacyPolicy: undefined;
  Terms: undefined;
  Support: undefined;
  LockSettings: undefined;
  TransactionAuditLogs: { mode: 'credit' | 'payment'; transactionId: number };
};
